export const homeObjOne={
    to:'/aboutme',
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Me',
    headLine: 'Lorem Ipsum',
    description: 'I am a student and an explorer. Some nuances of life confuse me and some leave me in deep thought. I try making the best (Lemonade 😉) out of my opportunities and am always willing to learn. Glad you landed on my page.',
    buttonLabel: 'Know More',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Face',
    dark: true,
    primary: true,
    darkText: false,
    targ:""
};
export const homeObjTwo={
    to:'/myeducation',
    id: 'education',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'My Education',
    headLine: 'Lorem Ipsum',
    description: 'I believe that education is one of the greatest tools with which we can change our lives. It is much more than just grades. I have tried exploring various fields through my studies and tried giving my best in everything. I believe in hands-on experience and always try implementing the same. Know more about my studies by downloading my resume.',
    buttonLabel: 'Download Resume',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'Face',
    dark: false,
    primary: false,
    darkText: true,
    targ:"_blank"
};
export const homeObjThree={
    to:'/moreskills',
    id: 'skills',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'My Skills',
    headLine: 'Lorem Ipsum',
    description: "With the world changing faster than ever I believe that learning new skills is the right way to go. In today's world it is important to have both technical and non-technical skills. Know more about some of my skills by clicking the button below.",
    buttonLabel: 'Know More',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: 'Face',
    dark: false,
    primary: false,
    darkText: true,
    targ:""
};